version: "3.8"
services:
  apache:
    image: php:7.4-apache
    volumes:
      - web-src:/var/www/html
    networks:
      - backend
      - frontend
    deploy:
      replicas: 1

  cache_server: 
    deploy:
      replicas: 1
    image: adesq/varnish:6.4
    ports:
      - 80:80
    networks:
      - frontend

  mariadb-cluster:
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == basededatos]
    image: toughiq/mariadb-cluster:2.1
    environment:
      - DB_SERVICE_NAME=mariadb-cluster
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appvoting
      - MYSQL_USER=appvotingadmin
      - MYSQL_PASSWORD=3NKR1PT3Dp4$$w0rd
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
   
  lb_mariadb:
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == basededatos]
    image: toughiq/maxscale:1.4.5
    ports:
      - 3306:3306
    environment:
      - DB_SERVICE_NAME=mariadb-cluster
      - ENABLE_ROOT_USER=1
    networks:
      - backend

  portainer:
    image: portainer/portainer
    ports:
      - 9000:9000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - backend

volumes:
  web-src:
  mysql-data:

networks:
  backend:
    name: backend
    driver: overlay
  frontend:
    name: frontend
    driver: overlay
