version: "3.8"
services:
  apache:
    image: adesq/php-apache
    volumes:
      - web-src:/var/www/localhost/htdocs
    networks:
      - frontend
      - backend
    ports:
      - "8080:8080"
    deploy:
      replicas: 1

  varnish:
    depends_on:
      - apache
    image: adesq/varnish:6.4
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: ingress
    networks:
      - frontend
      - backend
    deploy:
      replicas: 1

  mariadb:
    image: toughiq/mariadb-cluster:2.1
    environment:
      - DB_SERVICE_NAME=mariadb
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=appvoting
      - MYSQL_USER=appvotingadmin
      - MYSQL_PASSWORD=3NKR1PT3Dp4$$w0rd
    networks:
      - backend
    volumes:
      - mysql-data:/var/lib/mysql
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == basededatos]

  lb_mariadb:
    image: toughiq/maxscale:1.4.5
    ports:
      - target: 3306
        published: 3306
        protocol: tcp
        mode: ingress
    environment:
      - DB_SERVICE_NAME=mariadb
      - ENABLE_ROOT_USER=1
    networks:
      - backend
    deploy:
      replicas: 1
      placement:
        constraints: [node.hostname == basededatos]

volumes:
  web-src:
  mysql-data:

networks:
  backend:
    name: backend
    driver: overlay
  frontend:
    name: frontend
    driver: overlay

