version: "3.7"
services:
  apache:
    image: php:7.2-apache
    container_name: apache
    expose: 
      - 80
    volumes:
      - ./src:/var/www/html
  cache_server:
    image: varnish:6.4
    container_name: varnish
    volumes:
      - ./default.vcl:/etc/varnish/default.vcl
    ports:
      - 8080:80
    links:
      - apache
